<a href="https://colab.research.google.com/github/Shreya5i4/23wh1a05i4_javaprogrammes/blob/main/ML_Practice_28_09_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1= np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr3 = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

In [3]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(6,)
(3, 2)
(3, 2, 1)


In [4]:
#standard arrays
zeros = np.zeros((3,3)) #input is shape of the array
print(zeros)

ones = np.ones((3,4))
print(ones)

rand = np.random.rand(3,3)
print(rand)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.8571036  0.11939375 0.4125753 ]
 [0.20824056 0.91301977 0.43355814]
 [0.85665041 0.65536632 0.46204686]]


In [5]:
#reshape
arr1 = np.array([1,2,3,4,5,6,7,8], dtype=float)
print(arr1)
#not copies of arrays
reshape1_arr1 = arr1.reshape(2,4)
print(reshape1_arr1)
#if you change arr1, all references to it will also change
reshape2_arr1 = arr1.reshape(2,2,2)
print(reshape2_arr1)

arr1[0]= 10
print(reshape2_arr1)

[1. 2. 3. 4. 5. 6. 7. 8.]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
[[[10.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]]


In [6]:
arr1 = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#simple indexing
print(arr1[0,1,0])
print(arr1[0][1][0])

print(arr1[:,1])
print(arr1[0,:,:])

print(arr1[:,:,0])
print(arr1[:,:,0].shape)

3
3
[[3 4]
 [7 8]]
[[1 2]
 [3 4]]
[[1 3]
 [5 7]]
(2, 2)


In [8]:
#advanced indexing
print(arr1[[1,0]]) #print zeroth row twice
print(arr1[[True, True]])

[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#slicing
arr1 = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr2 = arr1[0:1,0:3] #slicing does not copy memory

print(arr1)
print(arr2)

arr2 = arr1[0,0:4:2] # slicing with stride
print(arr2)

arr2 = arr1[0,0:-1]
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]]
[1 3]
[1 2 3]


In [11]:
arr1 = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
arr2 = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)

print(arr1 + arr2) #elementwise addition
print(arr1 * arr2) #elementwise multiplication
print(arr1/ arr2)

[[ 2  4  6  8]
 [10 12 14 16]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
arr1 = arr1 = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
print(arr1)
print(arr1.sum()) #sum over entire arry
print(np.sum(arr1, axis=1)) #sums of specific axes/dimensions)

print(arr1.mean())
print(arr1.mean(axis=1))

[[1 2 3 4]
 [5 6 7 8]]
36
[10 26]
4.5
[2.5 6.5]


In [13]:
arr1 = np.random.rand(2,3)
arr2 = np.random.rand(3,2)

print(arr1 @ arr2)
print(np.dot(arr1,arr2))

[[0.97585941 0.59388059]
 [0.7279648  0.38083447]]
[[0.97585941 0.59388059]
 [0.7279648  0.38083447]]


In [14]:
# select all elements of an array greater than 0.5
arr = np.random.rand(3,5)
index = (arr >= 0.5)
print(arr[index])

[0.56681355 0.73884018 0.77020375 0.67425554 0.5244576  0.5220903
 0.99325481 0.64722136 0.79469757]


In [15]:
#from an array select all rows that sum to less than 2
arr = np.random.rand(5,4)
rowsum = arr.sum(axis=1)
print(arr[rowsum < 2])
print(arr[rowsum < 2].sum(1))

[[0.36144562 0.61507626 0.08322597 0.42112315]
 [0.00830476 0.27157379 0.54713094 0.86130739]]
[1.480871   1.68831689]


In [16]:
#replace all 0s with 2s
arr = (np.random.rand(5,4) > 0.5).astype(int)
print(arr)
index = (arr == 0)
arr[index] = 2
print(arr)

[[1 0 0 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 1 0 0]]
[[1 2 2 2]
 [2 2 1 1]
 [2 2 2 1]
 [2 2 2 1]
 [2 1 2 2]]


SKLEARN


In [17]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, SGDRegressor, Ridge, Lasso
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [18]:
#load dataset
diabetes = datasets.load_diabetes()
X = diabetes.data
Y = diabetes.target

In [19]:
#get test split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.25)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
print(X.shape)
print(X_train.shape, X_test.shape)

(442, 10)
(331, 10) (111, 10)


In [21]:
#linear regression
model = LinearRegression(fit_intercept=True)
#fitting linear regression model to data (TRAINING STEP)
_ = model.fit(X_train, Y_train)
#measure performance on test set
Y_pred = model.predict(X_test)

error  = mean_squared_error(Y_test, Y_pred)
r2 = model.score(X_test, Y_test)
print(error)
print(r2)
print(model.coef_)

3597.3641895736246
0.3614250924076571
[ -3.05668782  -9.57018968  24.10922656  19.14194817 -57.04928632
  37.41739984  14.05474707  14.46658806  44.67730238  -1.01369495]


In [22]:
#SGDRegressor
sgd_model = SGDRegressor()
sgd_model.fit(X_train, Y_train)
Y_pred = sgd_model.predict(X_test)
error = mean_squared_error(Y_test, Y_pred)
r2 = sgd_model.score(X_test, Y_test)
print(error)
print(r2)
print(sgd_model.coef_)

3482.7014530068536
0.38177909121034415
[-2.43671982 -9.20785282 25.44387339 18.5802002  -6.95811399 -2.12471938
 -8.05418981  8.14594257 24.80559031 -0.95929693]


In [23]:
#Ridge (Ridge is simply linear regression + a regularizer)
#A regularizer is something that is added to the loss function to improve training. You can think of it as something to stop the weights from becoming too large
ridge_model = Ridge()
ridge_model.fit(X_train, Y_train)
Y_pred = ridge_model.predict(X_test)
error = mean_squared_error(Y_test, Y_pred)
r2 = ridge_model.score(X_test, Y_test)
print(error)
print(r2)
print(ridge_model.coef_)

3553.8646962981443
0.36914676956762127
[ -2.828045    -9.41194551  24.37498279  18.90915613 -43.18480703
  26.43442136   7.90608018  12.60178673  39.07332915  -0.97507607]
